Elcodi\Component\Geo\Entity\Address:
    type: entity
    repositoryClass: Elcodi\Component\Geo\Repository\AddressRepository
    table: address
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        recipientName:
            column: recipient_name
            type: string
            length: 255
            nullable: true
        recipientSurname:
            column: recipient_surname
            type: string
            length: 255
            nullable: true
        address:
            column: address
            type: string
            length: 255
            nullable: false
        addressMore:
            column: address_more
            type: string
            length: 255
            nullable: true
        phone:
            column: phone
            type: string
            length: 255
            nullable: false
        mobile:
            column: mobile
            type: string
            length: 255
            nullable: true
        comments:
            column: comments
            type: text
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        city:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\CityInterface
            joinColumn:
                name: city_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"
        postalCode:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\PostalCodeInterface
            joinColumn:
                name: postal_code_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
