Elcodi\GeoBundle\Entity\Address:
    type: entity
    repositoryClass: Elcodi\GeoBundle\Repository\AddressRepository
    table: address
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        recipientName:
            column: recipient_name
            type: string
            length: 255
            nullable: true
        recipientSurname:
            column: recipient_surname
            type: string
            length: 255
            nullable: true
        address:
            column: address
            type: string
            length: 255
            nullable: false
        addressMore:
            column: address_more
            type: string
            length: 255
            nullable: true
        postalCode:
            column: postalcode
            type: string
            length: 255
            nullable: false
        city:
            column: city
            type: string
            length: 255
            nullable: false
        province:
            column: province
            type: string
            length: 255
            nullable: false
        state:
            column: state
            type: string
            length: 255
            nullable: false
        phone:
            column: phone
            type: string
            length: 255
            nullable: false
        mobile:
            column: mobile
            type: string
            length: 255
            nullable: true
        comments:
            column: comments
            type: text
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        country:
            targetEntity: Elcodi\GeoBundle\Entity\Interfaces\CountryInterface
            joinColumn:
                name: country_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
