Elcodi\Component\Geo\Entity\City:
    type: entity
    repositoryClass: Elcodi\Component\Geo\Repository\CityRepository
    table: city
    id:
        id:
            type: string
            generator:
                strategy: NONE
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        country:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\CountryInterface
            inversedBy: cities
            joinColumn:
                name: country_code
                referencedColumnName: code
        state:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\StateInterface
            inversedBy: cities
            joinColumn:
                name: state_id
                referencedColumnName: id
        province:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\ProvinceInterface
            inversedBy: cities
            joinColumn:
                name: province_id
                referencedColumnName: id
    manyToMany:
        postalCodes:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\PostalCodeInterface
            inversedBy: cities
            onDelete: "CASCADE"
            cascade:
                - "persist"
            joinTable:
                name: cities_postal_codes
                joinColumns:
                    city_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    postal_code_id:
                        referencedColumnName: id
