Elcodi\Component\Geo\Entity\Country:
    type: entity
    repositoryClass: Elcodi\Component\Geo\Repository\CountryRepository
    table: country
    id:
        code:
            type: string
            generator:
                strategy: NONE
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        enabled:
            column: enabled
            type: boolean
    oneToMany:
        states:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\StateInterface
            mappedBy: country
            onDelete: "CASCADE"
            cascade:
                - "persist"
        provinces:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\ProvinceInterface
            mappedBy: country
        cities:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\CityInterface
            mappedBy: country
