Elcodi\Component\Geo\Entity\PostalCode:
    type: entity
    repositoryClass: Elcodi\Component\Geo\Repository\PostalCodeRepository
    table: postalcode
    id:
        id:
            type: string
            generator:
                strategy: NONE
    fields:
        code:
            column: code
            type: string
            length: 255
            nullable: false
        enabled:
            column: enabled
            type: boolean

    manyToMany:
        cities:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\CityInterface
            mappedBy: postalCodes
