Elcodi\Component\Geo\Entity\Province:
    type: entity
    repositoryClass: Elcodi\Component\Geo\Repository\ProvinceRepository
    table: province
    id:
        id:
            type: string
            generator:
                strategy: NONE
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        code:
            column: code
            type: string
            length: 255
            nullable: false
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        country:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\CountryInterface
            inversedBy: provinces
            joinColumn:
                name: country_code
                referencedColumnName: code
        state:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\StateInterface
            inversedBy: provinces
            joinColumn:
                name: state_id
                referencedColumnName: id
    oneToMany:
        cities:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\CityInterface
            mappedBy: province
            onDelete: "CASCADE"
            cascade:
                - "persist"
