Elcodi\Component\Geo\Entity\ZoneMember:
    type: entity
    inheritanceType: JOINED
    table: zone_member
    repositoryClass: Elcodi\Component\Geo\Repository\ZoneMemberRepository
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        zone_country_member: Elcodi\Component\Geo\Entity\ZoneCountryMember
        zone_state_member: Elcodi\Component\Geo\Entity\ZoneStateMember
        zone_province_member: Elcodi\Component\Geo\Entity\ZoneProvinceMember
        zone_city_member: Elcodi\Component\Geo\Entity\ZoneCityMember
        zone_postal_code_member: Elcodi\Component\Geo\Entity\ZonePostalCodeMember
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
