Elcodi\Component\Geo\Entity\ZoneStateMember:
    type: entity
    table: zone_state_member
    manyToOne:
        state:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\StateInterface
            joinColumn:
                name: member_id
                referencedColumnName: id
