parameters:

    #
    # Factories
    #
    elcodi.factory.address.class: Elcodi\Component\Geo\Factory\AddressFactory
    elcodi.factory.location.class: Elcodi\Component\Geo\Factory\LocationFactory
    elcodi.factory.location_data.class: Elcodi\Component\Geo\Factory\LocationDataFactory

    #
    # Commands
    #
    elcodi.command.geo_populate.class: Elcodi\Component\Geo\Command\GeoPopulateCommand

    #
    # Controllers
    #
    elcodi.controller.location_api.class: Elcodi\Component\Geo\Controller\LocationApiController

    #
    # Services
    #
    elcodi.location_manager.service.class: Elcodi\Component\Geo\Services\LocationManager
    elcodi.location_manager.api_urls.class: Elcodi\Component\Geo\ValueObject\ApiUrls

    #
    # GeoData populator adapters
    #
    elcodi.populator.location.geoname.class: Elcodi\Component\Geo\Populator\Adapters\GeonamesPopulatorAdapter

    #
    # Transformers
    #
    elcodi.location_to_location_data_transformer.class: Elcodi\Component\Geo\Transformer\LocationToLocationDataTransformer
