parameters:

    #
    # Factories
    #
    elcodi.factory.address.class: Elcodi\Component\Geo\Factory\AddressFactory
    elcodi.factory.location.class: Elcodi\Component\Geo\Factory\LocationFactory
    elcodi.factory.location_data.class: Elcodi\Component\Geo\Factory\LocationDataFactory

    #
    # Commands
    #
    elcodi.command.location_populate.class: Elcodi\Component\Geo\Command\LocationPopulateCommand

    #
    # Controllers
    #
    elcodi.controller.location_api.class: Elcodi\Component\Geo\Controller\LocationApiController

    #
    # Services
    #
    elcodi.location_provider.service.class: Elcodi\Component\Geo\Services\LocationServiceProvider
    elcodi.location_provider.api.class: Elcodi\Component\Geo\Services\LocationApiProvider
    elcodi.location_api_urls.class: Elcodi\Component\Geo\ValueObject\ApiUrls
    elcodi.location_builder.class: Elcodi\Component\Geo\Services\LocationBuilder
    elcodi.manager.address.class: Elcodi\Component\Geo\Services\AddressManager

    #
    # Location populators
    #
    elcodi.location_populator.class: Elcodi\Component\Geo\Populator\Interfaces\PopulatorInterface
    elcodi.location_populator.geoname.class: Elcodi\Component\Geo\Populator\Adapters\GeonamesPopulatorAdapter

    #
    # Transformers
    #
    elcodi.transformer.location_to_location_data.class: Elcodi\Component\Geo\Transformer\LocationToLocationDataTransformer

    #
    # EventDispatcher
    #
    elcodi.event_dispatcher.address.class: Elcodi\Component\Geo\EventDispatcher\AddressEventDispatcher
