parameters:

    #
    # Factories
    #
    elcodi.factory.address.class: Elcodi\Component\Geo\Factory\AddressFactory
    elcodi.factory.location.class: Elcodi\Component\Geo\Factory\LocationFactory
    elcodi.factory.location_data.class: Elcodi\Component\Geo\Factory\LocationDataFactory

    #
    # Commands
    #
    elcodi.core.geo.command.geo_populate.class: Elcodi\Component\Geo\Command\GeoPopulateCommand

    #
    # Services
    #
    elcodi.core.geo.populator.geo_populator.class: Elcodi\Component\Geo\Populator\GeoPopulator
    elcodi.core.geo.builder.geo_builder.class: Elcodi\Component\Geo\Builder\GeoBuilder
    elcodi.location_manager.service.class: Elcodi\Component\Geo\Services\LocationManager

    #
    # GeoData populator adapters
    #
    elcodi.geo.dummy_populator_adapter.class: Elcodi\Component\Geo\Adapter\Populator\DummyPopulatorAdapter
    elcodi.geo.geodata_populator_adapter.class: Elcodi\Component\Geo\Adapter\Populator\GeoDataPopulatorAdapter

    #
    # Transformers
    #
    elcodi.location_to_location_data_transformer.class: Elcodi\Component\Geo\Transformer\LocationToLocationDataTransformer