services:

    #
    # Commands
    #
    elcodi.command.geo_populate:
        class: %elcodi.command.geo_populate.class%
        arguments:
            - @elcodi.geo_populator
            - @elcodi.director.location
        tags:
            -  { name: console.command }
