services:

    #
    # Commands
    #
    elcodi.command.location_populate:
        class: %elcodi.command.location_populate.class%
        arguments:
            - @elcodi.location_populator
            - @elcodi.director.location
        tags:
            -  { name: console.command }
