services:

    #
    # Commands
    #
    elcodi.core.geo.command.geo_populate:
        class: %elcodi.core.geo.command.geo_populate.class%
        arguments:
            geo_populator: @elcodi.geo_populator
        tags:
            -  { name: console.command }
