services:

    #
    # Commands
    #
    elcodi.command.location_populate:
        class: Elcodi\Component\Geo\Command\LocationPopulateCommand
        arguments:
            - @elcodi.location_populator
            - @elcodi.director.location
            - @elcodi.factory.datetime
        tags:
            -  { name: console.command }
