services:

    #
    # Factories
    #

    #
    # Factory for entity address
    #
    elcodi.core.geo.factory.address:
        class: %elcodi.core.geo.factory.address.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.address.class%"]]

    elcodi.factory.address:
        alias: elcodi.core.geo.factory.address

    elcodi.core.geo.factory.country:
        class: %elcodi.core.geo.factory.country.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.country.class%"]]

    elcodi.factory.country:
        alias: elcodi.core.geo.factory.country

    #
    # Entity providers
    #

    #
    # Instance provider for entity address
    #
    elcodi.core.geo.entity.address.instance:
        class: %elcodi.core.geo.entity.address.class%
        factory_service: elcodi.core.geo.factory.address
        factory_method: create
        scope: prototype

    elcodi.entity.address.instance:
        alias: elcodi.core.geo.entity.address.instance

    #
    # Instance provider for entity country
    #
    elcodi.core.geo.entity.country.instance:
        class: %elcodi.core.geo.entity.country.class%
        factory_service: elcodi.core.geo.factory.country
        factory_method: create
        scope: prototype

    elcodi.entity.country.instance:
        alias: elcodi.core.geo.entity.country.instance
