services:

    #
    # Factories
    #

    #
    # Factory for entity address
    #
    elcodi.factory.address:
        class: %elcodi.factory.address.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.address.class%"]]

    elcodi.factory.location:
        class: %elcodi.factory.location.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.location.class%"]]

    elcodi.factory.location_data:
        class: %elcodi.factory.location_data.class%
