services:

    #
    # Object Managers
    #
    elcodi.object_manager.country:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            cart_namespace: %elcodi.core.geo.entity.country.class%
