parameters:

    #
    # Parameters
    #
    elcodi.location_api_route_get_root_locations: %elcodi.location_api_prefix%/root
    elcodi.location_api_route_get_children: %elcodi.location_api_prefix%/children
    elcodi.location_api_route_get_parents: %elcodi.location_api_prefix%/parents
    elcodi.location_api_route_get_location: %elcodi.location_api_prefix%/location
    elcodi.location_api_route_get_hierarchy: %elcodi.location_api_prefix%/hierarchy
    elcodi.location_api_route_in: %elcodi.location_api_prefix%/in
