services:

    #
    # GeoData populator adapters
    #
    elcodi.populator.location.geoname:
        class: %elcodi.populator.location.geoname.class%
        arguments:
            - @elcodi.extractor
            - @elcodi.factory.location

    #
    # Extractor
    #
    elcodi.extractor:
        class: Mmoreram\Extractor\Extractor
        arguments:
            - @elcodi.extractor.directory
            - @elcodi.extractor.extension_resolver

    elcodi.extractor.directory:
        class: Mmoreram\Extractor\Filesystem\TemporaryDirectory
        public: false

    elcodi.extractor.extension_resolver:
        class: Mmoreram\Extractor\Resolver\ExtensionResolver
        public: false
