services:

    #
    # Services
    #
    elcodi.location_manager.service:
        class: %elcodi.location_manager.service.class%
        arguments:
            location_repository: @elcodi.repository.location
            location_data_factory: @elcodi.factory.location_data
