services:

    #
    # Services
    #
    elcodi.location_provider.service:
        class: Elcodi\Component\Geo\Services\LocationServiceProvider
        arguments:
            - @elcodi.repository.location
            - @elcodi.transformer.location_to_location_data

    elcodi.location_provider.api:
        class: Elcodi\Component\Geo\Services\LocationApiProvider
        arguments:
            - @elcodi.factory.location_data
            - @elcodi.location_api_urls

    elcodi.location_api_urls:
        class: Elcodi\Component\Geo\ValueObject\ApiUrls
        arguments:
            - %elcodi.location_api_host%%elcodi.location_api_route_get_root_locations%
            - %elcodi.location_api_host%%elcodi.location_api_route_get_children%
            - %elcodi.location_api_host%%elcodi.location_api_route_get_parents%
            - %elcodi.location_api_host%%elcodi.location_api_route_get_location%
            - %elcodi.location_api_host%%elcodi.location_api_route_get_hierarchy%
            - %elcodi.location_api_host%%elcodi.location_api_route_in%

    elcodi.location_builder:
        class: Elcodi\Component\Geo\Services\LocationBuilder
        arguments:
            - @elcodi.factory.location

    elcodi.manager.address:
        class: Elcodi\Component\Geo\Services\AddressManager
        arguments:
            - @elcodi.object_manager.address
            - @elcodi.event_dispatcher.address
