services:

    #
    # Transformers
    #
    elcodi.transformer.location_to_location_data:
        class: %elcodi.transformer.location_to_location_data.class%
        arguments:
            location_data_factory: @elcodi.factory.location_data
