services:

    #
    # Transformers
    #
    elcodi.location_to_location_data_transformer:
        class: %elcodi.location_to_location_data_transformer.class%
        arguments:
            location_data_factory: @elcodi.factory.location_data