parameters:

    #
    # GeoDataPopulator Adapter
    #
    elcodi.core.geo.adapter.geodata_populator_adapter.class: Elcodi\Component\Geo\Adapter\Populator\GeoDataPopulatorAdapter

services:

    #
    # GeoDataPopulator Adapter
    #
    elcodi.core.geo.adapter.geodata_populator_adapter:
        class: %elcodi.core.geo.adapter.geodata_populator_adapter.class%
        arguments:
            geo_builder: @elcodi.geo_builder

    elcodi.core.geo.adapter.populator_adapter:
        alias: elcodi.core.geo.adapter.geodata_populator_adapter
